<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <InvariantGlobalization>true</InvariantGlobalization>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <PublishAot>true</PublishAot>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>../WindBot.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.0-preview.5.23280.1" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\Config.cs" />
    <Compile Include="..\Game\AI\Deck.cs" />
    <Compile Include="..\Game\AI\Decks\*.cs" />
    <Compile Include="..\Game\DecksManager.cs" />
    <Compile Include="..\Game\GameBehavior.cs" />
    <Compile Include="..\Game\GameClient.cs" />
    <Compile Include="..\Game\GamePacketFactory.cs" />
    <Compile Include="..\Game\Room.cs" />
    <Compile Include="..\Logger.cs" />
    <Compile Include="..\Program.cs" />
    <Compile Include="..\Properties\AssemblyInfo.cs" />
    <Compile Include="..\WindBotInfo.cs" />
    <Compile Include="..\YGOSharp.Network\AsyncBinaryClient.cs" />
    <Compile Include="..\YGOSharp.Network\AsyncNetworkServer.cs" />
    <Compile Include="..\YGOSharp.Network\AsyncYGOClient.cs" />
    <Compile Include="..\YGOSharp.Network\BinaryClient.cs" />
    <Compile Include="..\YGOSharp.Network\Enums\CtosMessage.cs" />
    <Compile Include="..\YGOSharp.Network\Enums\GameState.cs" />
    <Compile Include="..\YGOSharp.Network\Enums\PlayerChange.cs" />
    <Compile Include="..\YGOSharp.Network\Enums\PlayerState.cs" />
    <Compile Include="..\YGOSharp.Network\Enums\PlayerType.cs" />
    <Compile Include="..\YGOSharp.Network\Enums\StocMessage.cs" />
    <Compile Include="..\YGOSharp.Network\NetworkClient.cs" />
    <Compile Include="..\YGOSharp.Network\NetworkServer.cs" />
    <Compile Include="..\YGOSharp.Network\Utils\BinaryExtensions.cs" />
    <Compile Include="..\YGOSharp.Network\YGOClient.cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="ExecutorBase.csproj">
      <Project>{a1583fd7-7985-47dd-a835-8134dbf5811c}</Project>
      <Name>ExecutorBase</Name>
    </ProjectReference>
  </ItemGroup>
  <ItemGroup>
    <TrimmerRootDescriptor Include="DontTrimTypes.xml" />
  </ItemGroup>
</Project>
